# Generated by Django 6.0.2 on 2026-03-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(blank=True, choices=[('core', 'core'), ('commercial', 'commercial'), ('arts', 'arts'), ('science', 'science'), ('vocational', 'vocational'), ('language', 'language')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
