# Generated by Django 6.0.2 on 2026-03-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_read_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
