# Generated by Django 6.0.2 on 2026-03-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
