# Generated by Django 6.0.2 on 2026-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprofile',
            name='voice_pref',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=25, null=True),
        ),
    ]
