# Generated by Django 6.0.2 on 2026-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
