# Generated by Django 6.0.2 on 2026-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_referral_code_user_referred_by_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
