# Generated by Django 6.0.2 on 2026-03-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examprofile',
            name='learning_format',
        ),
    ]
